spring:
  profiles:
    active: dev
---
server:
  port: 6001

spring:
  profiles: dev
  application:
    name: mecroservice-config-eureka

eureka:
  instance:
    hostname: eureka6001.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://eureka6002.com:6002/eureka
  server:
    enable-self-preservation: false

---

server:
  port: 6001

spring:
  profiles: prod
  application:
    name: mecroservice-config-eureka

eureka:
  instance:
    hostname: eureka6001.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://eureka6002.com:6002/eureka
  server:
    enable-self-preservation: true